# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/rocks_bot',
                'doc_host': 'https://udaylunawat.github.io',
                'git_url': 'https://github.com/udaylunawat/rocks_bot',
                'lib_path': 'rocks_bot'},
  'syms': { 'rocks_bot.data.download': {'rocks_bot.data.download.get_data': ('a_datasets.html#get_data', 'rocks_bot/data/download.py')},
            'rocks_bot.data.utils': {}}}