# Autogenerated by nbdev

d = { 'settings': { 'branch': 'nbdev',
                'doc_baseurl': '/Whats-this-rock',
                'doc_host': 'https://udaylunawat.github.io',
                'git_url': 'https://github.com/udaylunawat/Whats-this-rock',
                'lib_path': 'rocks_classifier'},
  'syms': { 'rocks_classifier.core': {'rocks_classifier.core.foo': ('core.html#foo', 'rocks_classifier/core.py')},
            'rocks_classifier.data.download': { 'rocks_classifier.data.download.download_datasets': ( 'b_download.html#download_datasets',
                                                                                                      'rocks_classifier/data/download.py')},
            'rocks_classifier.data.preprocess': {},
            'rocks_classifier.data.utils': { 'rocks_classifier.data.utils.find_filepaths': ( 'a_download_utils.html#find_filepaths',
                                                                                             'rocks_classifier/data/utils.py'),
                                             'rocks_classifier.data.utils.get_new_name': ( 'a_download_utils.html#get_new_name',
                                                                                           'rocks_classifier/data/utils.py'),
                                             'rocks_classifier.data.utils.move_to_processed': ( 'a_download_utils.html#move_to_processed',
                                                                                                'rocks_classifier/data/utils.py'),
                                             'rocks_classifier.data.utils.timer_func': ( 'a_download_utils.html#timer_func',
                                                                                         'rocks_classifier/data/utils.py')}}}