project:
  type: website
  preview:
    port: 3000
format:
  html:
    page-layout: full
    theme: dark
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml, custom.yml]
