# defaults:
#   - dataset: [1, 2, 3, 4]
#   - optimizer: adamax

notes: ""
seed: 42

lr: 0.001
lr_decay_steps: 500
lr_schedule: cosine_decay

epochs: 30
class_weights: True
optimizer: adam
loss: categorical_crossentropy
metrics: ["accuracy"]
batch_size: 32
num_classes: 7
custom_callback: True
monitor: "val_accuracy"

# dataset
dataset_id: [1]
data_path: data/4_tfds_dataset/
sampling: None
train_split: 0.70
image_size: 224
image_channels: 3
augmentation: True

# model
backbone: resnet
use_pretrained_weights: True
preprocess: True
dropout_rate: 0.3
save_model: False
trainable: True
last_layers: 30

# wandb
wandb:
  use: True
  project: Whats-this-rockv10
  mode: offline

# callback
earlystopping:
  use: False
  patience: 10

reduce_lr:
  use: False
  factor: 0.6
  min_lr: 1e-5
  patience: 2
