method: bayes
metric:
  goal: maximize
  name: val_f1_score
parameters:
  notes:
    value: ""
  seed:
    value: 42
  lr:
    values: [1e-3, 5e-4, 1e-4, 5e-5, 1e-5]
  epochs:
    value: 30
  augmentation:
    value: True
  class_weights:
    value: True
  optimizer:
    values: [adam, adamax]
  loss:
    value: categorical_crossentropy
  metrics:
    value: ["accuracy"]
  batch_size:
    value: 64
  num_classes:
    value: 7
  data_path:
    value: data/4_tfds_dataset/
  use_wandb:
    value: True
  wand_mode:
    value: online
  project:
    value: Whats-this-rockv3
  dataset_id:
    value: [1, 2, 3, 4]
  image_size:
    value: 224
  image_channels:
    value: 3
  sampling:
    values: [None, oversampling, undersampling]
  backbone:
    values: [efficientnetv2m, efficientnetv2, resnet, mobilenetv2]
  use_pretrained_weights:
    values: [True, False]
  trainable:
    values: [True, False]
  preprocess:
    value: True
  dropout_rate:
    value: 0.3
  monitor:
    value: "val_f1_score"
  earlystopping_patience:
    value: 10=
  reduce_lr_factor:
    values: [.9, .7, .5]
  reduce_lr_patience:
    values: [1, 2, 3, 4]
  reduce_lr_min_lr:
    value: 0.00001
  save_model:
    value: True

program: src/models/train.py
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
