method: bayes
metric:
  goal: minimize
  name: val_loss
parameters:
  notes:
    value: ""
  seed:
    values: [1]
  lr:
    distribution: uniform
    min: 1e-5
    max: 1e-4
  epochs:
    value: 50
  augmentation:
    value: True
  class_weights:
    value: True
  optimizer:
    values: [adam]
  loss:
    value: categorical_crossentropy
  metrics:
    value: ["accuracy"]
  batch_size:
    value: 64
  num_classes:
    value: 7
  train_split:
    values:
      - 0.80
  data_path:
    value: data/4_tfds_dataset/
  wandb.use:
    value: True
  wandb.mode:
    value: online
  wandb.project:
    value: Whats-this-rockv7
  dataset_id:
    values:
      - [1]
  image_size:
    value: 224
  image_channels:
    value: 3
  sampling:
    values: [None, oversampling]
  backbone:
    values: [resnet]
  use_pretrained_weights:
    values: [True]
  trainable:
    values: [False]
  last_layers:
    values: [5, 10, 20, 30]
  custom_callback:
    values: [True, False]
  preprocess:
    value: True
  dropout_rate:
    values: [0, 0.1, 0.3, 0.5]
  monitor:
    values: ["val_loss"]
  earlystopping.use:
    values: [False]
  earlystopping.patience:
    values: [10]
  reduce_lr.use:
    values: [True]
  reduce_lr.factor:
    values: [.9, .3]
  reduce_lr.patience:
    values: [1, 5]
  reduce_lr.min_lr:
    values: [parameters.lr/100]
  save_model:
    value: False

program: src/models/train.py
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
