method: bayes
metric:
  goal: maximize
  name: val_f1_score
parameters:
  notes:
    value: "Datasets:[1,2,3,4], train shuffle :True, Augment: 9 augmentations,
            sampling: None, removing_corrupt: False"
  augment:
    values: [true]
  finetune:
    values: [false]
  freeze:
    values: [false]
  pretrained_model_link:
    value: "rock-classifiers/Whats-this-rockv2/cvzc7hq0"
  batch_size:
    values: [32]
  metrics:
    value: ["accuracy"]
  max_epochs:
    value: 100
  loss_fn:
    value: "categorical_crossentropy"
  lr:
    values: [1e-3, 5e-4, 1e-4, 5e-5, 1e-5]
  model_name:
    values: ["efficientnet"]
  optimizer:
    values: ["adam"]
  image_size:
    value: 224
  earlystopping_patience:
    value: 10
  earlystopping_min_delta:
    value: 0.02
  lr_reduce_patience:
    values: [1, 2, 3, 4]
  lr_reduce_factor:
    values: [.9, .7]
  threshold:
    value: 0.7
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 100
program: src/train.py