method: bayes
metric:
  goal: maximize
  name: val_accuracy
parameters:
  notes:
    value: ""
  seed:
    value: [1, 42, 100]
  lr:
    values: [1e-3, 5e-4, 1e-4, 5e-5, 1e-5]
  epochs:
    value: 100
  augmentation:
    value: True
  class_weights:
    value: True
  optimizer:
    values: [adam, adamax]
  loss:
    value: categorical_crossentropy
  metrics:
    value: ["accuracy"]
  batch_size:
    value: 64
  num_classes:
    value: 7
  train_split:
    values: [0.7, 0.75, 0.80]
  data_path:
    value: data/4_tfds_dataset/
  use_wandb:
    value: True
  wand_mode:
    value: online
  project:
    value: Whats-this-rockv3
  dataset_id:
    values:
      - [1]
  image_size:
    value: 224
  image_channels:
    value: 3
  sampling:
    values: [None, oversampling, undersampling]
  backbone:
    values:
      [
        efficientnetv2m,
        efficientnetv2,
        resnet,
        mobilenetv2,
        inceptionresnetv2,
        xception,
      ]
  use_pretrained_weights:
    values: [True]
  trainable:
    values: [True, False]
  preprocess:
    value: True
  dropout_rate:
    values: [0.3]
  monitor:
    value: "val_accuracy"
  use_earlystopping:
    value: True
  earlystopping_patience:
    value: 20
  use_reduce_lr:
    values: [True, False]
  reduce_lr_factor:
    values: [.9, .7, .5, .3]
  reduce_lr_patience:
    values: [1, 3, 5, 7, 13]
  reduce_lr_min_lr:
    value: 1e-5
  save_model:
    value: False

program: src/models/train.py
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}
