name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  nbdev-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
        with:
          skip_test: true

  test-notebooks:
    needs: test-nbdev-sync
    runs-on: ubuntu-latest
    steps:
    - name: download-data
      run: rocks_download_data
    - name: Test notebooks
      run: nbdev_test --flags '' --do_print --timing
