name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test-nbdev-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: fastai/workflows/nbdev-ci@master
        with:
          skip_test: true
      - name: Download and extract data.
        run: rocks_download_data
      - name: Test notebooks
        run: nbdev_test --flags '' --do_print --timing
